# SyncroSim in R {#rssim}

Along with using SyncroSim from the GUI, one of the goals of this project was to create functional SyncroSim scripts in the R package rsyncrosim that could then, with very little editing, be repurposed to run the same kinds of spatial realizations using other landscapes, particularly without having to do any work in GIS-specific software.

This objective sprang out of the Conservation Data Lab, and from the R scripting work of mentor and founding member Myles Waalima. As a project of Randy Swaty's and an affiliate of The Nature Conservancy, the CDL and its constituent members do a good deal of work with LANDFIRE products: as such, Myles' original code takes the GRID directory files for LANDFIRE's biophysical setting, succession class, existing vegetation cover, existing vegetation height, existing vegetation type, vegetation departure, and mean fire return interval geospatial products, clips them to the extent of an input shape file, and then returns both a set of new, clipped rasters and a series of charts and tables visualizing landscape data in terms of metrics like degree of vegetation departure by succession class. It was his work to take as input a continental-United-States-wide data file, clip it, and return a relevant raster which I built upon in the rsyncrosim package, with the idea of producing a stock code which might, with the input of LANDFIRE data and a shapefile, return a model of a landscape under different management classes, or at least of the impact of the predominant biophysical setting on that landscape.

The documentation for rsyncrosim can be found at https://cran.r-project.org/web/packages/rsyncrosim/rsyncrosim.pdf, and was for the most part enormously helpful in writing code to run SyncroSim through R. I would strongly recommend familiarizing ones self with SyncroSim through the GUI before scripting simulations in R, but after doing so, it becomes easy enough to figure out what calls to make by using the datasheet() call on any level of your project. Lower levels report out the function names for higher level aspects of the work under a category called "scope", so a datasheet(myScenario) call will give you access to the name in rsyncrosim paired with the name used in the SyncroSim GUI of any aspect of your work you want to edit - the only downside of calling the scenario, rather than project or library, is that it extends the results, which can make them more difficult to read.

Because running a spatial model requires setting the model ID, my code makes several basic assumptions to do with biophysical setting. The first is that there any given project (and, indeed, library), has only one state and transition simulation model associated with it. While this may not be true for other uses of stsim, because the state classes can only be indexed to one model at a time, I feel it is a fair assumption to make about any model run with LANDFIRE data. The second is that this singular model is based in whichever BpS is most represented on the chosen landscape, with the metric of representation measured in raw pixel count. If this is not the case, the sheetData$ID variable can be manually changed in the code to whichever ID is most appropriate, but this is the base functionality.

As with the model ID, in any STSM run from scratch, state class IDs must also be set for SyncroSim to function properly. However, unlike with the model, where BpS names cannot be extracted from the raster, and as such the automation of the ID requires some assumption, the structure of LANDFIRE BpS data allows for unambiguous automated value assignment. The script reads in a CSV file containing all of the LANDFIRE S classes and then loops sequentially through that list, comparing its contents to that of the state classes in the StSim model. Because the state class raster values always ascend in a predictable order and by single integers, despite not spanning all available S classes they can still be reliably valued.

I had sorted out all of this, and with it the other issues which arise when working with an unfamiliar software package (yes, it's worth checking your working directory again, even though you're 100% sure you already checked it), and, while I was able to execute a blank-slate-to-full-SyncroSim-realization code run, I could not then extract any of the resultant rasters from R. They clearly existed: when I checked SyncroSim, I could view the maps for every simulated transition, but all attempts to produce them in R resulted in the code aborting with a message that the package I was attempting to call did not exist. 

Some troubleshooting later, I discovered a peculiarity of the rsyncrosim package. While most calls in rsyncrosim make specific reference to the SyncroSim package they're requesting - a datasheet save addressed to "stsim_Stratum", for example, can modify the values in the primary tab of the SyncroSim project level - the datasheetRaster function takes only the second half of that argument. Rather than telling datasheetRaster to look in "stsim_OutputSpatialState" for the desired spatial outputs, it takes the argument "OutputSpatialState" only, and then concatenates the package name to the front. 

In stsim, the primary SyncroSim package for state and transition simulation modeling, this is probably a perfectly good shorthand. To the best of my knowledge, the state and transition simulation modeling done in Syncrosim with LANDFIRE data has thus far overwhelmingly emphasized non-spatial models, with even less work done in running the landfirevegmodels package through R rather than the GUI. With the landfirevegmodels package in SyncroSim comes all of the state and transition models for every biophysical setting across the United States and affiliated territories, and the package loads into the SyncroSim GUI an export feature which makes it easy to isolate a particular model. So long as you don't want to extract any rasters from your simulations to R, this works perfectly fine. Rasters can be copied from SyncroSim to the clipboard and thus extracted.

The other option, and the one I took, is to instead do all work from the stsim LANDFIRE library, which can be downloaded separately from http://landfirereview.org/search.php. The process of extracting models becomes slightly more time consuming - you have to copy the library, delete every model but the model of interest from the project layer of the folder, and then use the compress function from the File menu on the newly shrunken library - but not substantially more difficult. Because the model is now running in the stsim package, all work can then be done in R without conflict.

After finishing the code to feed in your own data and from that, crop and run a raster, I added a secondary, much shorter code, which extracts a raster from a spatial run previously done in SyncroSim.