# Next Steps {#next}

With limited time in a quarter and other obligations and responsibilities, my work on the Wayne National Forest was far from exhaustive. Practical and proof of concept work in R and SyncroSim, with a focus on state and transition simulation modeling predominated, while the connectivity work, which turned out to be more challenging in both concept and execution than expected, didn't quite make it off the ground during this time frame.

This is not the end of my work with The Nature Conservancy and the Conservation Data Lab, as I plan to continue this project at least throughout the summer, though the bulk and product-oriented side of it will likely be handed off to Randy Swaty and those with more in-depth knowledge of ecology and in particular the ecological systems prevalent on the Wayne than I possess. My ongoing work will likely focus more in the gaps and lumps in the procedure and the viability of extending spatial modeling into Omniscape for connectivity work. 

First and foremost, if there is ever to be any desire to use these models for actual policy directives, the problem with spatially-propagating transitions needs to be addressed. A map which comes out of a SyncroSim simulation unrealistically patchwork is useless for connectivity modeling and adds almost no information to that which gain be obtained from a non-spatial model. Following Randy's general directive to go down rabbit holes for about ten hours, and then, if not making progress on something, to move on, I abandoned that train of thought when it became a clear breakpoint in my ability to get anything done, but now that I'm on my own time and nobody can stop me, it really is a critical distinction between work that is cool but lacks practical purpose and genuine information which can be used to generate more information.

As an addendum to this, creating transition types to model for management interventions such as harvest and whatever else the Wayne National Forest thinks is important, as well as adding states for uncharacteristic natural and exotic vegetation, _if_ the spatial work can be made to cooperate both in the propagation of fire and in Omniscape connectivity models, to begin assessing the value of actual management strategies. This was something that Randy and I discussed several times as an objective for this probject, and work that I am blazingly underqualified for, as became clear to me when I tried paramaterizing a resistance raster for a baseline Omniscape run using LANDFIRE's current geospatial data. The raster values I created will work fine for proof of concept and method development, which is really where my skills and role in this project lie, but I know nothing about the difference between "mid-seral closed Tuliptree" and "mixed white pine and oak and other things with underlying laurels" and it shows. 

My second continuing goal is to develop an understanding of Omniscape and a methodology such that so long as transition-propagating rasters can be generated, they can easily be run in Omniscape. I've had significant trouble trying to make and parameterize resistance rasters, as mentioned above, and I don't expect the actual numerical results from my realizations to be of any planning value, but I would like to finish out our original connectivity goals. Early in the project, too, Kim Hall suggested continuing work in testing the robustness of connectivity models to fine-grained changes in resistance values and then reporting out on it, an idea which has seized me by the left brain and refused to let go, and developing a strong familiarity with Omniscape and an ability to run it with at least functional, if not sensible models is important in that effort.

Third, and as a more auxiliary goal, I would like to practice some Cloud-based computing. This was something Randy and I began pursuing through Amazon Web Services, in response to the computing power necessary to run multiple synchronous spatial realizations in SyncroSim overrunning my laptop's memory and the time needed to run them sequentially being impractical. While I don't believe that the current state of the SyncroSim models merits any more than superficial test runs, particularly given the lack of spatial propagation, it is an important skill for me to develop, and if we get to the point of running models that are informative from a land-management perspective, it will be a necessary resource. Essentially: we've already started, might as well continue.

Leaving room for any work I do with the Conservation Data Lab to exceed these bounds, these are my objectives for this project beyond my graduation, and with this bookdown record maintained as a living document as to the process and outcomes, to eventually be completed as a record of the Wayne National Forest project in its entirety.